### ISSUE TITLE
NO JBOVLASTE DEFINITION FOR "???" FOUND!

### ISSUE THREAD

**Issue by nesiax** [lojban/cll#100]
Hi, I am building the documentation but I got the following error:

NO JBOVLASTE DEFINITION FOR "a" FOUND!
NO JBOVLASTE DEFINITION FOR "a" FOUND!
NO JBOVLASTE DEFINITION FOR "abu" FOUND!
[...]

Does the script point to the jbovlaste website to retrieve the definitions ? Is the URL outdated ?

**Comment by nyarly** [comment]
The URL is current, but jbovlaste has added a captcha - presumably since the script was written. Since it doesn't re-get the file each time, it seems easy for the maintainers to miss the issue.

Fortunately, it also seems easy to work around: go to http://jbovlaste.lojban.org/export/xml-export.html?lang=en, perform the captcha yourself and save it as jbovlaste.xml in the root of the work directory.

**Comment by rlpowell** [comment]
It can also be fixed in the code by adding a special password
parameter:

http://jbovlaste.lojban.org/export/xml-export.html?lang=art-loglan&bot_key=z2BsnKYJhAB0VNsl

-Robin

On Fri, Nov 29, 2013 at 11:55:01AM -0800, Judson Lester wrote:

> The URL is current, but jbovlaste has added a captcha - presumably since the script was written. Since it doesn't re-get the file each time, it seems easy for the maintainers to miss the issue.
> 
> Fortunately, it also seems easy to work around: go to http://jbovlaste.lojban.org/export/xml-export.html?lang=en, perform the captcha yourself and save it as jbovlaste.xml in the root of the work directory.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/dag/cll/issues/100#issuecomment-29535149

## 

http://intelligence.org/ :  Our last, best hope for a fantastic future.
.i ko na cpedu lo nu stidi vau loi jbopre .i danfu lu na go'i li'u .e
lu go'i li'u .i ji'a go'i lu na'e go'i li'u .e lu go'i na'i li'u .e
lu no'e go'i li'u .e lu to'e go'i li'u .e lu lo mamta be do cu sofybakni li'u

**Comment by nyarly** [comment]
Is that something we could add to the build script? Or not something we want in the repo?

**Comment by rlpowell** [comment]
We could totally add it, I just haven't yet.

-Robin

On Fri, Nov 29, 2013 at 01:10:41PM -0800, Judson Lester wrote:

> Is that something we could add to the build script? Or not something we want in the repo?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/dag/cll/issues/100#issuecomment-29537782

## 

http://intelligence.org/ :  Our last, best hope for a fantastic future.
.i ko na cpedu lo nu stidi vau loi jbopre .i danfu lu na go'i li'u .e
lu go'i li'u .i ji'a go'i lu na'e go'i li'u .e lu go'i na'i li'u .e
lu no'e go'i li'u .e lu to'e go'i li'u .e lu lo mamta be do cu sofybakni li'u

**Comment by rlpowell** [comment]
This appears to be fine now.
