### ISSUE TITLE
Ask for translative permission

### ISSUE THREAD

**Issue by Gompyn** [lojban/cll#256]
As Chinese, we lack the Chinese version of CLL, so we ask you for a permission here.

**Comment by lagleki** [comment]
At the time this book was written CreativeCommons license didn't exist. However, the book has:

http://lojban.github.io/cll/1/8/

```
Permission is granted to make and distribute verbatim copies of this book, either in electronic or in printed form, provided the copyright notice and this permission notice are preserved on all copies.

Permission is granted to copy and distribute modified versions of this book, provided that the modifications are clearly marked as such, and provided that the entire resulting derived work is distributed under the terms of a permission notice identical to this one.

*Permission is granted to copy and distribute translations of this book into another language, under the above conditions for modified versions, except that this permission notice may be stated in a translation that has been approved by the Logical Language Group, rather than in English.*

The contents of Chapter 21 are in the public domain.
```

If you mean that "approved by the Logical Language Group" then you may start translating unofficially just now.

I'm a member of LLG and pretty sure you will get that permission.

However, LLG will need to approve some already existing translation.

**Comment by guskant** [comment]
As written in Chapter 1 Section 8, you don't need permission for translating the CLL. The part 
"[...] this permission notice may be stated in a translation that has been approved by the Logical Language Group, rather than in English."
states only an optional permission about the permission notice itself in Chapter 1 Section 8. Moreover, that permission notice _may_ (not "must") be written in any language other than English, and that part _may_ be approved by the Logical Language Group.
